extends Node

# Single source of truth for equipment slot IDs and item main_type metadata.
# Adding a new slot or main_type is a one-file change here; ItemRoller,
# InventoryState, CharacterPanel, and tooltips all read from these consts.
#
# Slot IDs are StringName so dict lookups across the codebase hash the same
# way. Main_type strings stay plain strings — they're authored in affix
# tables and weapon-base resources as readable labels (`"1H Weapon"`,
# `"Backpack"`) and need to round-trip through .tres serialisation.

# Equipment slot IDs in canonical iteration order. UI grids may impose their
# own row/column layout (CharacterPanel.EQUIP_SLOTS) but the slot ID set is
# defined here.
#
# `&"weapon_2"` / `&"weapon_3"` / `&"weapon_4"` are PERK-GATED — they only
# accept items when the Forged Amalgamation perk grants enough extra arms
# (PerkState.get_aggregate(&"extra_weapon_slots")). Listed here for the
# canonical-set property; UI hides them when locked.
const SLOTS: Array[StringName] = [
	&"head", &"chest", &"hands",
	&"weapon", &"backpack", &"offhand",
	&"legs", &"feet", &"consumable",
	&"weapon_2", &"weapon_3", &"weapon_4",
]

# Perk-gated extra weapon slots, in unlock order. Index N is granted when
# extra_weapon_slots aggregate >= N+1.
const EXTRA_WEAPON_SLOTS: Array[StringName] = [
	&"weapon_2", &"weapon_3", &"weapon_4",
]


## True when the slot is one of the perk-gated extra weapon slots. Extras
## reject 2H weapons (each extra arm wields a 1H), and the slot only accepts
## items at all when the perk grants enough extra arms.
func is_extra_weapon_slot(slot: StringName) -> bool:
	return slot in EXTRA_WEAPON_SLOTS

# Item main_types eligible for random rolling. `"Offhand"` is generated by
# starter helpers but isn't in the random pool yet, so it doesn't appear
# here — keeps roll_random from producing a category that has no weapon-base
# variants behind it.
const MAIN_TYPES: Array[String] = [
	"1H Weapon", "2H Weapon",
	"Head Armor", "Chest Armor", "Gloves", "Leg Armor", "Boots",
	"Backpack", "Grenade", "Consumable",
]

# main_type → slot lookup. Both weapon variants resolve to the same slot
# (`&"weapon"`); two-handed display logic lives on Item.two_handed.
const MAIN_TYPE_TO_SLOT: Dictionary = {
	"1H Weapon":   &"weapon",
	"2H Weapon":   &"weapon",
	"Offhand":     &"offhand",
	"Head Armor":  &"head",
	"Chest Armor": &"chest",
	"Gloves":      &"hands",
	"Leg Armor":   &"legs",
	"Boots":       &"feet",
	"Backpack":    &"backpack",
	"Grenade":     &"offhand",
	"Consumable":  &"consumable",
}

const MAIN_TYPE_GLYPH: Dictionary = {
	"1H Weapon":   "†",
	"2H Weapon":   "‡",
	"Offhand":     "◊",
	"Head Armor":  "▲",
	"Chest Armor": "▣",
	"Gloves":      "Ψ",
	"Leg Armor":   "⌠",
	"Boots":       "⌐",
	"Backpack":    "▤",
	"Grenade":     "◉",
	"Consumable":  "+",
}


## Slot ID for a rolled main_type. Returns &"" when the type is unknown —
## callers should treat that as "unequipable" rather than mis-routing it.
func slot_for_type(main_type: String) -> StringName:
	return MAIN_TYPE_TO_SLOT.get(main_type, &"")


## Display glyph for a main_type. Falls back to "?" so UIs don't render an
## empty cell when a new type slips through without a glyph entry.
func glyph_for_type(main_type: String) -> String:
	return MAIN_TYPE_GLYPH.get(main_type, "?")
