extends Node

# Single source of truth for equipment slot IDs and item main_type metadata.
# Adding a new slot or main_type is a one-file change here; ItemRoller,
# InventoryState, CharacterPanel, and tooltips all read from these consts.
#
# Slot IDs are StringName so dict lookups across the codebase hash the same
# way. Main_type strings stay plain strings — they're authored in affix
# tables and weapon-base resources as readable labels (`"1H Weapon"`,
# `"Backpack"`) and need to round-trip through .tres serialisation.

# Equipment slot IDs in canonical iteration order. UI grids may impose their
# own row/column layout (CharacterPanel.EQUIP_SLOTS) but the slot ID set is
# defined here. `&"mainboard"` sits outside the 9-cell visible grid for now;
# expanded UIs reference it directly when they need to.
const SLOTS: Array[StringName] = [
	&"head", &"optics", &"backpack",
	&"weapon", &"chest", &"offhand",
	&"gloves", &"belt", &"boots",
	&"mainboard",
]

# Item main_types eligible for random rolling. `"Offhand"` is generated by
# starter helpers but isn't in the random pool yet, so it doesn't appear
# here — keeps roll_random from producing a category that has no weapon-base
# variants behind it.
const MAIN_TYPES: Array[String] = [
	"1H Weapon", "2H Weapon",
	"Head Armor", "Chest Armor", "Gloves", "Boots",
	"Belt", "Mainboard", "Backpack", "Optics",
]

# main_type → slot lookup. Both weapon variants resolve to the same slot
# (`&"weapon"`); two-handed display logic lives on Item.two_handed.
const MAIN_TYPE_TO_SLOT: Dictionary = {
	"1H Weapon":   &"weapon",
	"2H Weapon":   &"weapon",
	"Offhand":     &"offhand",
	"Head Armor":  &"head",
	"Chest Armor": &"chest",
	"Gloves":      &"gloves",
	"Boots":       &"boots",
	"Belt":        &"belt",
	"Mainboard":   &"mainboard",
	"Backpack":    &"backpack",
	"Optics":      &"optics",
}

const MAIN_TYPE_GLYPH: Dictionary = {
	"1H Weapon":   "†",
	"2H Weapon":   "‡",
	"Offhand":     "◊",
	"Head Armor":  "▲",
	"Chest Armor": "▣",
	"Gloves":      "Ψ",
	"Boots":       "⌐",
	"Belt":        "═",
	"Mainboard":   "⌬",
	"Backpack":    "▤",
	"Optics":      "✦",
}


## Slot ID for a rolled main_type. Returns &"" when the type is unknown —
## callers should treat that as "unequipable" rather than mis-routing it.
func slot_for_type(main_type: String) -> StringName:
	return MAIN_TYPE_TO_SLOT.get(main_type, &"")


## Display glyph for a main_type. Falls back to "?" so UIs don't render an
## empty cell when a new type slips through without a glyph entry.
func glyph_for_type(main_type: String) -> String:
	return MAIN_TYPE_GLYPH.get(main_type, "?")
